### PR TITLE
Added Roadmap and Future Plans

### LINKED ISSUE #5: Create Road Map and Future plans in README

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fix #5 
Changes: Added Roadmap and Future Plans

### CODE REVIEW

**Comment by srv-twry** [comment]
@harsh-jindal Any reason why you closed other PR's specially the one which was approved and only needed to be squashed ?

**Comment by harsh-jindal** [comment]
Sir I squashed the 2 commits then pushed(it got squashed into 1 and then I tried pushing but it asked me to pull first and after pull) then it created two more new commits in the same branch.
Then I tried deleting the last 2 commits and everything got (all the 4 commits) deleted(then all this happened).
 So I created new branch and again made the pull request. I'm still trying to learn git so sorry for the many closed PR's. I still didn't figure out how to change(or correct) the commit after making a pull request for it.

**Comment by srv-twry** [comment]
@harsh-jindal  No issues 
You can learn about squashing [here](https://github.com/NJACKWinterOfCode/IITP-Connect/pull/21)

**Comment by harsh-jindal** [comment]
Okay..

**Comment by harsh-jindal** [comment]
Thanks I understood my mistake.

**Pull request merged**
