### PR TITLE
Added Roadmap and Future Plans

### LINKED ISSUE #5: Create Road Map and Future plans in README

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fix #5 
Changes: Added Roadmap and Future Plans

### CODE REVIEW

**Comment by harsh-jindal** [comment]
Its resolved.

**Comment by srv-twry** [comment]
@harsh-jindal Kindly squash these two commits into one. You can learn about it [here](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git/5201642#5201642)

**Comment by harsh-jindal** [comment]
Okay

**Comment by ShikharJ** [comment]
@harsh-jindal You don't need to create a new PR every time you make a change. You just need to do a force push to the existing branch and the PR will be updated automatically. Please force push in the future. Otherwise it is difficult to keep track of the developer conversation across different PRs.

**Comment by harsh-jindal** [comment]
Okay. Sorry for the many PR's created and closed.

**Pull request closed without merging**
