### PR TITLE
Added App Icon

### LINKED ISSUE #6: Design the app icon
**Actual Behaviour**

No app icon exists.

**Expected Behaviour**

App icon should be designed.

Proper discussion about the design and color scheme should be done before working on it.

### PR DESCRIPTION
**Pull request by AK-007**
Fix #6 

Changes: Added launcher icon for the app.

Screenshots for the change:
appicon

### CODE REVIEW

**Comment by ShikharJ** [comment]
@srv-twry @mayank8318 @AK-007 I think it'd be better if there was some distance between the "T" of "IIT" and the Wi-fi symbol (like there's a distance between the two "I"s). Also, I think it'd be better if the Wi-fi symbol was in white, like the rest of the text. Thoughts?

**Comment by AK-007** [comment]
Actually the wifi symbol makes a P along with T , adding distance between them may not be a good idea.

**Comment by srv-twry** [comment]
@ShikharJ Then he would have to insert another character 'P' in the design.

**Comment by srv-twry** [comment]
@chiragw15 @jtatia Your thoughts on this design ? 
You can also look at [this](https://github.com/NJACKWinterOfCode/IITP-Connect/issues/6) discussion for alternatives

**Comment by mayank8318** [comment]
Colour of the Wifi symbol needs a change. Otherwise it looks nice.

**Comment by ShikharJ** [comment]
@AK-007 [Here](https://github.com/NJACKWinterOfCode/IITP-Connect/issues/6#issuecomment-347483809) is the original design that was intended. I am rooting for this one. cc @srv-twry @mayank8318

**Comment by AK-007** [comment]
Should I make a the wifi color same as IIT.....it looks good that way too.

**Comment by srv-twry** [comment]
@AK-007 Yeah make it white too.

**Comment by AK-007** [comment]
demo

**Comment by AK-007** [comment]
How about this @ShikharJ @srv-twry 
sdsd

**Comment by srv-twry** [comment]
@AK-007 Nice ! let's wait for other's views.

**Comment by Kartik2016** [comment]
@AK-007 Wow the icon looks really cool !

**Pull request merged**
